<?php

/**
 * Implements hook_og_context_negotiation_info().
 */
function og_path_context_og_context_negotiation_info() {
  $providers = array();

  $providers['og_path_context'] = array(
    'name' => t('Path'),
    'description' => t('Select groups by checking if the path of the current page matches the path of an OG group node. Parts are removed from the end of the path, then re-checked until, a match is found or there are no more path parts.'),
    'callback' => 'og_path_context_handler_path',
  );

  return $providers;
}


/**
 * Context handler; Get groups from node create URL.
 */
function og_path_context_handler_path() {
  $gids = array();

  $item = menu_get_item();

  if (empty($item['map'])) {
    // User has no access to the menu item.
    return;
  }

  $path = $item['map'];

  $try = count($path);

  for ($i = 0; $i < $try; $i++) {
    $path_try = implode('/', $path);
    $system_path = drupal_get_normal_path($path_try);

    if (substr($system_path, 0, 5) == 'node/' && is_numeric(substr($system_path, 6))) {
      $nid = substr($system_path, 5);
      $node = node_load($nid);

      if (isset($node->group_group)) {
        return _group_context_handler_entity('node', $node);
      }

    }

    array_pop($path);
  }

  return;
}
