name = Site Frontend Two Column with left-hand navigation
description = 12 Column grid layout with first sidebar and main content, but without second sidebar
template = site-frontend-two-column-nav-layout
preview = preview.png

; Regions - these also need to exist in site_frontend.info
regions[header_branding] = Header Branding
regions[header_top_menu] = Header Top Menu
regions[header_search] = Header Search
regions[header_main_menu] = Header Main Menu
regions[header_social_media] = Header Social Media
regions[breadcrumb] = Breadcrumb
regions[accessibility] = Accessibility
regions[preface] = Preface
regions[content_top] = Content Top
regions[system_highlighted] = System Highlighted
regions[system_help] = System Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[node_inline] = Node inline
regions[bottom_menu] = Bottom Menu
regions[footer_social_media] = Footer Social Media
regions[footer_copyright] = Footer Copyright
regions[footer_menu] = Footer Menu
regions[footer_buttons] = Footer Buttons
regions[page_bottom] = Page Bottom

; following region is rendered in node.tpl.php for some content types
regions[node_inline] = Node Inline

; Styles
stylesheets[all][] = css/layouts/site-frontend-two-column-nav/site-frontend-two-column-nav.layout.css
stylesheets[all][] = css/layouts/site-frontend-two-column-nav/site-frontend-two-column.layout.no-query.css
