<?php

/**
 * Implements hook init
 */
function social_tab_init(){
  if ((arg(0) == 'admin') || (arg(0) == 'node' && arg(1) == 'add') || (arg(0) == 'node' && arg(2) == 'edit')) {
    return;
  }

  drupal_add_js('var addthis_config = {"data_track_addressbar":false, "data_use_cookies":false};','inline'); // enable address bar tracking feature
  drupal_add_js('//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5200e0ef1b2ac26f','external');
}
/**
 * Implements hook_theme().
 */
function social_tab_theme() {
  $theme = array(
    'social_tab_block' => array(
      'render element' => 'social_tab_block'
    ),
    'social_inline_block' => array(
      'render element' => 'social_inline_block'
    ),
  );
  return $theme;
}

/**
 * Implements hook_block_info().
 */
function social_tab_block_info() {

  $blocks['social_tab'] = array(
    'info' => t('Social Tab'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['social_inline'] = array(
    'info' => t('Social Inline Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function social_tab_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'social_tab':
      $block['subject'] = NULL;
      $block['content'] = array('#theme' => 'social_tab_block');
      break;
    case 'social_inline':
      $block['subject'] = t('Share this');
      $block['content'] = array('#theme' => 'social_inline_block');
      break;
  }
  return $block;
}

function theme_social_tab_block() {

  /*
  $output = '<!-- AddThis Tab BEGIN -->
               <div class="addthis_toolbox addthis_floating_style addthis_counter_style" style="position: fixed; right:0px; top:70px;">
                 <a class="addthis_button_facebook_like" fb:like:layout="box_count"></a>
                 <a class="addthis_button_tweet" tw:count="vertical"></a>
                 <a class="addthis_button_google_plusone" g:plusone:size="tall"></a>
                 <a class="addthis_counter"></a>
                 <a href="https://live.sagepay.com/MySagePay" target="_blank" class="mysagepay-login"></a>
               </div>
             <!-- AddThis Button END -->';
  */
  $output = '
  <div class="addthis_toolbox addthis_floating_style addthis_counter_style" style="position: fixed; right:0px; top:70px;" >
    <a href="https://live.sagepay.com/MySagePay" target="_blank" class="mysagepay-login"></a>
  </div>
  ';

  return $output;
}

function theme_social_inline_block() {
  $output = '<!-- AddThis Inline BEGIN -->
  <ul>
	<li><a class="addthis_button_facebook">Facebook</a></li>
	<li><a class="addthis_button_twitter">Twitter</a></li>
	<li><a class="addthis_button_google_plusone_share">Google Plus</a></li>
	<li><a class="addthis_button_email">Email</a></li>
</ul>


             <!-- AddThis Button END -->';

  return $output;
}
