<?php
/**
 * @file
 * Module file for the Food Standards Scotland module
 */

function _unpublish_scotland_pages() {
  // Get existing nodes
  $query = db_select( 'node', 'n' )
   ->fields( 'n', array('nid', 'title', 'status'));

  // Left join with the alias table
  $query->leftJoin( 'url_alias', 'ua', "ua.source = CONCAT('node/', n.nid)");

  // Select only published nodes
  $query->condition('n.status', 0, '>');

  // Select nodes where the URL alias starts with 'scotland'
  $query->condition('ua.alias', 'scotland/%', 'like');

  // Get the URL alias field
  $query->addField('ua', 'alias');

  // Execute the query.
  $results = $query->execute();

  // For each query result, unpublish the node.
  foreach ($results as $result) {
    if (!empty($result->nid) && !empty($result->title)) {
      $node = node_load($result->nid);
      $node->status = 0;
      node_save($node);
      $maxlength = 50;
      $title = strlen($result->title) > $maxlength ? substr($result->title, 0, $maxlength) . '...' : $result->title;
      echo "Unpublished node " . $result->nid . ' - ' . $title . ' - ' . 'http://www.food.gov.uk/' . $result->alias . PHP_EOL;
    }
  }

  // Display a finished message.
  return t('All Scottish nodes unpublished.');  
}
