<?php
/**
 * @file
 * Module file for accessibility_links.
 */


/**
 * Implements hook_theme().
 */
function accessibility_links_theme() {
  $theme = array(
    'accessibility_links_block' => array(
      'variables' => array(
        'accessibility_page_url' => 'about-us/data-and-policies/aboutsite/accessibility',
      ),
      'template' => 'theme/accessibility-links',
    )
  );
  return $theme;
}

/**
 * Implements hook_block_info().
 */
function accessibility_links_block_info() {
  $blocks['accessibility_links'] = array(
    'info' => t('Accessibility Links'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function accessibility_links_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'accessibility_links':
      $block['subject'] = NULL;
      $block['content'] = array(
        '#theme' => 'accessibility_links_block',
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'accessibility_links') . '/accessibility_links.css',
          ),
          'js' => array(
            drupal_get_path('module', 'accessibility_links') . '/accessibility_links.js',
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Preprocess function for accessibility links template.
 *
 * @param array $variables
 *   Template variables - passed by reference.
 *
 * @see accessibility-links.tpl.php
 * @see local_site_get_domain()
 * @see local_url_outbound_alter()
 */
function template_preprocess_accessibility_links_block(&$variables) {
  // We pass the accessibility page URL through the url() function, which in
  // turn calls local_url_outbound_alter(). This works out whether we're on a
  // committee site using one of the committee subdomains and substitutes an
  // absolute URL based on the domain defined in local_site_get_domain().
  // This fixes issue #1030 - broken accessibility link on committee pages
  $variables['accessibility_page_url'] = url($variables['accessibility_page_url']);
}
