<?php
/**
 * @file
 * Module file for accessibility_links.
 */

/**
 * Implements hook init
 */
function accessibility_links_init(){
	drupal_add_css(drupal_get_path('module', 'accessibility_links') . '/accessibility_links.css');
	drupal_add_js(drupal_get_path('module', 'accessibility_links') . '/accessibility_links.js');
}

/**
 * Implements hook_theme().
 */
function accessibility_links_theme() {
  $theme = array(
    'accessibility_links_block' => array(
      'render element' => 'accessibility_links_block'
    )
  );
  return $theme;
}

/**
 * Implements hook_block_info().
 */
function accessibility_links_block_info() {
  $blocks['accessibility_links'] = array(
    'info' => t('Accessibility Links'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function accessibility_links_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'accessibility_links':
      $block['subject'] = NULL;
      $block['content'] = array('#theme' => 'accessibility_links_block');
      break;
  }
  return $block;
}

function theme_accessibility_links_block() {
  // get the current site
  //$site = 'www.food.gov.uk';
  $site = $_SERVER['HTTP_HOST'];
  $output = '<div id="accessTools">
                <form name="dixeritRefererForm" id="dixeritRefererForm" method="post" action="http://spoxy3.insipio.com/generator/en/'. $site .'/">
                    <div><input type="hidden" name="referer" value=""></div>
                </form>
                <p>Access tools</p>
                <ul>
                    <li id="accessListen"><a href="http://spoxy3.insipio.com/generator/en/'. $site .'/" title="Listen to this site">Listen <span class="icon"></span></a></li>
	                <li><a href="/about-us/data-and-policies/aboutsite/accessibility/">Accessibility</a></li>
	                <li><a href="">Text only</a></li>
	                <li id="fontScale"><a id="fontScale0" class="fontScalePlus0" href="#" title="Set font size to default">A</a> <a id="fontScale1" class="fontScalePlus1" href="#" title="Set font size to +1">A</a> <a id="fontScale2" class="fontScalePlus2" href="#" title="Set font size to +2">A</a></li>
	            </ul>
	        </div>';
  return $output;
}
