<?php

/**
 * @file
 * Provide blocks that contain other blocks.
 *
 * In order to group a set of different facetapi blocks toghether in one
 * container, we have needed to generate the blocks in a pre-process.
 *
 * To find the facetAPI id:
 * - add the facet block to the page as usual
 * - inspect the block
 * - find the facet id
 * - add to the container block
 * - remove the facet block (as it will now be in the container block)
 *
 *
 * Views exposed filters are defined in this format:
 * exp-[view machine name as in view url]-[view display name]
 *    e.g. -exp-news_centre___search-page
 */

/**
 * Implements hook_block_info().
 */
function container_blocks_block_info() {
  $blocks['search_all_facets'] = array(
    'info' => t('Search All Facets'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['search_all_news_facets'] = array(
    'info' => t('Search All News Facets'),
  );

  $blocks['search_all_news_facets_food_alerts'] = array(
    'info' => t('Search All News Facets (food alerts)'),
  );
  
  $blocks['search_all_news_facets_allergy_alerts'] = array(
    'info' => t('Search All News Facets (food alerts)'),
  );

  $blocks['search_news_facets_scotland'] = array(
    'info' => t('Search All News Facets (Scotland)'),
  );

  $blocks['search_news_facets_ireland'] = array(
    'info' => t('Search All News Facets (Ireland)'),
  );

  $blocks['search_news_facets_wales'] = array(
    'info' => t('Search All News Facets (Wales)'),
  );

  $blocks['search_news_facets_wales_welsh'] = array(
    'info' => t('Search All News Facets (Wales in welsh)'),
  );

  $blocks['search_alerts_facets'] = array(
    'info' => t('Search Alerts Facets'),
  );

  $blocks['search_guidance'] = array(
    'info' => t('Search Guidance'),
  );

  $blocks['search_consultations'] = array(
    'info' => t('Search Consultations'),
  );

  $blocks['search_audit_reports'] = array(
    'info' => t('Search Audit Reports'),
  );

  $blocks['search_committee_papers'] = array(
    'info' => t('Search Committee Papers'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function container_blocks_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'search_all_facets':

      $blocks[] = block_load('views', '-exp-search_sitewide-page');
      $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      $blocks[] = block_load('facetapi', 'JA1S7gqOdiVJQxg5zwM1Pb8KjhJNGZjx');

      // Guidance dependant facets
      $blocks[] = block_load('facetapi', '2114gf0ekix3fbtdoanmoe1w9krmhxv4');
      $blocks[] = block_load('facetapi', 'p3fubrie0j3kxs8j2aewwxks2gqtkmih');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_all_news_facets':
      if ($delta == 'search_all_news_facets' ) {
        $blocks[] = block_load('views', '-exp-news_centre___search-page');
      }
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // updated time facet
      // $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
      // Nation
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_all_news_facets_nations':
       // a version of the news facets that does not have an option to filter by nation
      $blocks[] = block_load('views', '-exp-news_centre___search-page');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;


    case 'search_news_facets_ireland':
      // a version of the news facets that does not have an option to filter by nation
      $blocks[] = block_load('views', '-exp-nations___news_updates_news-page');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;
    case 'search_news_facets_scotland':
      // a version of the news facets that does not have an option to filter by nation
      $blocks[] = block_load('views', '-exp-nations___news_updates_news-page_1');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;
    case 'search_news_facets_wales':
      // a version of the news facets that does not have an option to filter by nation
      $blocks[] = block_load('views', '-exp-nations___news_updates_news-page_2');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;
    case 'search_news_facets_wales_welsh':
      // a version of the news facets that does not have an option to filter by nation
      $blocks[] = block_load('views', '-exp-nations___news_updates_news-page_3');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_alerts_facets':
      $blocks[] = block_load('views', '-exp-alerts-page');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');


      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_guidance':
      $blocks[] = block_load('views', '-exp-search_sitewide-page');
      $blocks[] = block_load('facetapi', '2114gf0ekix3fbtdoanmoe1w9krmhxv4');
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      $blocks[] = block_load('facetapi', 'p3fubrie0j3kxs8j2aewwxks2gqtkmih');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;

    case 'search_consultations':
      // Nation
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');
      //status
      $blocks[] = block_load('facetapi', 'x4nnoysr1rqw1vfaghilcfbruu0t1ml1');
      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;

    case 'search_audit_reports':
      // Nation.
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      // Audit type.
      $blocks[] = block_load('facetapi', 'nad0zwsdksumabkwgcngpas5iikhjfmw');
      // Audit state.
      $blocks[] = block_load('facetapi', 'rki2uwj1stot4co2v0tkak5avuy4ilhi');
      // Authority type.
      $blocks[] = block_load('facetapi', 'osdqst08lgwyuqprmimxdogailt1qynk');
      // Last updated year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');
      // Has Action Plan.
      $blocks[] = block_load('facetapi', 'ae1hugfdpdtovvqzvnuos6xa7bkpit9h');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;

    case 'search_committee_papers':
      // Published Year.
      $blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');
      // Freetag Topic.
      $blocks[] = block_load('facetapi', 'hz3me3m90tyr28bumoupbsr1tvm009r8');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;
      
      case 'search_all_news_facets_food_alerts':
	// select the appropriate exposed filters for this block.
	($delta == 'search_food_alerts_facets') 
	  $blocks[] = block_load('views', '-exp-news_centre___search-page_1');
	$blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
	// updated time facet
	// $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
	// Nation
	$blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
	// Last updated year.
	$blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');

	$content = container_blocks_concatenate_content($blocks);

	$block['subject'] = NULL;
	$block['content'] = array(
	  '#markup' => $content,
	);
            
      break;  
      
      case 'search_all_news_facets_allergy_alerts':
	// select the appropriate exposed filters for this block.
	($delta == 'search_allergy_alerts_facets') 
	  $blocks[] = block_load('views', '-exp-news_centre___search-page_2');
	$blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
	// updated time facet
	// $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
	// Nation
	$blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
	// Last updated year.
	$blocks[] = block_load('facetapi', 'z0n0mr7e3co9o4fke31fjmkzq9qgwfqq');
  
	$content = container_blocks_concatenate_content($blocks);
  
	$block['subject'] = NULL;
	$block['content'] = array(
	  '#markup' => $content,
	);
      }
      
      break;
      
  }
  return $block;
}

/**
 * Implements hook_block_view().
 * @param $blocks Array Array of blocks
 */
function container_blocks_concatenate_content($blocks) {
  $content = '';

  foreach ($blocks as $block) {
    $render = _block_get_renderable_array(_block_render_blocks(array($block)));
    $content .= drupal_render($render);
  }

  return $content;
}

