<?php

/**
 * @file
 * Provide blocks that contain other blocks.
 */

/**
 * Implements hook_block_info().
 */
function container_blocks_block_info() {
  $blocks['search_all_facets'] = array(
    'info' => t('Search All Facets'),
  );

  $blocks['search_all_dependant_facets'] = array(
    'info' => t('Search All Dependant Facets'),
  );

  $blocks['search_all_news_facets'] = array(
    'info' => t('Search All News Facets'),
  );

  $blocks['search_guidance'] = array(
    'info' => t('Search Guidance'),
  );

  $blocks['search_consultations'] = array(
    'info' => t('Search Consultations'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function container_blocks_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'search_all_facets':

      $blocks[] = block_load('views', '-exp-search_sitewide-page');
      $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      $blocks[] = block_load('facetapi', 'JA1S7gqOdiVJQxg5zwM1Pb8KjhJNGZjx');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_all_dependant_facets':

      $blocks[] = block_load('facetapi', '2114gf0ekix3fbtdoanmoe1w9krmhxv4');
      $blocks[] = block_load('facetapi', 'p3fubrie0j3kxs8j2aewwxks2gqtkmih');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;

    case 'search_all_news_facets':

      $blocks[] = block_load('views', '-exp-news_centre___search-page');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_guidance':
      $blocks[] = block_load('views', '-exp-search_sitewide-page');
      $blocks[] = block_load('facetapi', '2114gf0ekix3fbtdoanmoe1w9krmhxv4');
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      $blocks[] = block_load('facetapi', 'p3fubrie0j3kxs8j2aewwxks2gqtkmih');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;

    case 'search_consultations':
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');
      $blocks[] = block_load('facetapi', 'x4nnoysr1rqw1vfaghilcfbruu0t1ml1');
      $blocks[] = block_load('facetapi', '4oshdock6vikervr03r0jhzo1vob4nh5');

      $content = container_blocks_concatenate_content($blocks);

      if (!empty($content)) {

        $block['subject'] = NULL;
        $block['content'] = array(
          '#markup' => $content,
        );
      }

      break;
  }
  return $block;
}

/**
 * Implements hook_block_view().
 */
function container_blocks_concatenate_content($blocks) {
  $content = '';

  foreach ($blocks as $block) {
    $content .= drupal_render(_block_get_renderable_array(_block_render_blocks(array($block))));
  }

  return $content;
}
