<?php

/**
 * @file
 * Provide blocks that contain other blocks.
 */

/**
 * Implements hook_block_info().
 */
function container_blocks_block_info() {
  $blocks['search_all_facets'] = array(
    'info' => t('Search All Facets'),
  );

  $blocks['search_all_news_facets'] = array(
    'info' => t('Search All News Facets'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function container_blocks_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'search_all_facets':

      $blocks[] = block_load('views', '-exp-search_sitewide-page');
      $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');
      $blocks[] = block_load('facetapi', 'JA1S7gqOdiVJQxg5zwM1Pb8KjhJNGZjx');
      $blocks[] = block_load('facetapi', 'ly6396gbtdufodpd8je0qyujejn73bws');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;

    case 'search_all_news_facets':

      $blocks[] = block_load('views', '-exp-news_centre___search-page');
      $blocks[] = block_load('facetapi', 'mo10eVoL905Qwndxck1XcD0dZWgc0x7s');
      $blocks[] = block_load('facetapi', 'bLPXAQDJqA1Re1OTSoyUJM9gUBaIgZMG');

      $content = container_blocks_concatenate_content($blocks);

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => $content,
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_block_view().
 */
function container_blocks_concatenate_content($blocks) {
  $content = '';

  foreach ($blocks as $block) {
    $content .= drupal_render(_block_get_renderable_array(_block_render_blocks(array($block))));
  }

  return $content;
}
