<?php
/**
 * Created by PhpStorm.
 * User: Peter
 * Date: 07/07/14
 * Time: 16:34
 */

/**
 * Implements hook_menu().
 *
 * Set up admin settings callbacks, etc.
 */
function FSA_menu_build_menu() {
  $items = array();
  $items['admin/menubuild'] = array(
    'title' => 'Menubuild',
    'description' => 'Build menus after migration.',
    'page callback' => 'FSA_menu_build_page',
    'access arguments' => array('administer site'),
  );
  return $items;
}

/**
* Page controller.
 */
function FSA_menu_build_page(){
  $output = "test";
  // build a tree of all migrated nodes
  $url_tree = FSA_menu_build_process_list(FSA_menu_build_get_url_list());

  // now, recurse through the tree, and assign menu parents
  FSA_menu_build_assign($url_tree);
  variable_set('menu_rebuild_needed', TRUE);
  return $output;
}

function FSA_menu_build_get_list_from_CSV($file){

}

/**
 * Retrieve the list of urls to process
 */
function FSA_menu_build_get_url_list($file = null){
  if (!$file) {
    $url_list = array(
   // 'test-1',
    //'test1/test2',
    //'test1/test2/test/test3',
    //'test-1/test-1-1/test1-1-1',
    //'test-1/test1-2',
      '/business-industry/allergy-guide/gluten/gluten-faq-caterers/',
      '/business-industry/caterers/food-hygiene/charity-community-groups/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animalfeedaddfaq/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/canthaxanthin_qanda/',
      '/business-industry/farmingfood/bse/what/',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/operators/',
      '/business-industry/farmingfood/fish-shellfish/freezing-requirements/',
      '/business-industry/farmingfood/mycotoxins/questions/',
      '/business-industry/farmingfood/pesticides/pestfaq/',
      '/business-industry/farmingfood/primprodqanda/',
      '/business-industry/farmingfood/vetmeds/vetmedfaq/',
      '/business-industry/farmingfood/wildgameguidance/wild-game-faq/',
      '/business-industry/imports/importers/thirdcountryfaq/',
      '/business-industry/imports/want_to_import/personalimports/',
      '/business-industry/winestandards/winefaq/',
      '/business-industry/allergy-guide/',
      '/business-industry/allergy-guide/gluten/',
      '/business-industry/caterers/',
      '/business-industry/caterers/food-hygiene/',
      '/business-industry/caterers/food-hygiene/butchers/',
      '/business-industry/caterers/food-hygiene/food-waste/',
      '/business-industry/caterers/food-hygiene/premises-hygiene/',
      '/business-industry/caterers/food-hygiene/premises-hygiene/movable-temp-premises/',
      '/business-industry/caterers/food-hygiene/schoolfood',
      '/business-industry/caterers/food-hygiene/water-supply/',
      '/business-industry/caterers/food-law-inspections/',
      '/business-industry/caterers/haccp/',
      '/business-industry/caterers/hygieneratings/',
      '/business-industry/caterers/hygieneratings/fhrsbackground/',
      '/business-industry/caterers/hygieneratings/fhrsbackground/citizens-forums/',
      '/business-industry/caterers/hygieneratings/fhrsbackground/sotdconsultation/',
      '/business-industry/caterers/hygieneratings/fhrsbackground/sotdcorrespondence/',
      '/business-industry/caterers/hygieneratings/fhrsbackground/sotdevaluation',
      '/business-industry/caterers/hygieneratings/toolkit/',
      '/business-industry/caterers/hygieneratings/ukschemes/',
      '/business-industry/caterers/sfbb/',
      '/business-industry/caterers/sfbb/carehomes/',
      '/business-industry/caterers/sfbb/sfbbcaterers/',
      '/business-industry/caterers/sfbb/sfbbchildminders/',
      '/business-industry/caterers/sfbb/sfbbcolleges/',
      '/business-industry/caterers/sfbb/sfbbcuisines/',
      '/business-industry/caterers/sfbb/sfbblanguages/',
      '/business-industry/caterers/sfbb/sfbbretail/',
      '/business-industry/caterers/startingup/',
      '/business-industry/caterers/startingup/childminders/',
      '/business-industry/caterers/startingup/distanceguide',
      '/business-industry/caterers/training/',
      '/business-industry/caterers/training/hygiene-videos',
      '/business-industry/exports/',
      '/business-industry/farmingfood/',
      '/business-industry/farmingfood/animalfeed/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animal-feed-legislation-summary/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animal-feed-legislation-summary/animal-feed-legislation-ni/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animal-feed-legislation-summary/animal-feed-scotland-summary/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animal-feed-legislation-summary/animal-feed-summary-eng/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/animal-feed-legislation-summary/animal-feed-summary-wales/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/approvregfeedguidance',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/export-unauthorised-feed',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/feed-fats-oils-guidance/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/feed-fats-oils-guidance/feed-fat-oils-monitoring/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/feedundesirables',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/food-and-drink-businesses/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/guidfarm',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/market-use-animal-feed/',
      '/business-industry/farmingfood/animalfeed/animalfeedlegislation/pet-food/',
      '/business-industry/farmingfood/animalfeed/review-of-official-feed-controls-delivery/',
      '/business-industry/farmingfood/animalfeed/what-farm-animals-eat/',
      '/business-industry/farmingfood/bse/',
      '/business-industry/farmingfood/bse/controls',
      '/business-industry/farmingfood/cleaner-animals/',
      '/business-industry/farmingfood/cleaner-animals/flocks/',
      '/business-industry/farmingfood/crops/',
      '/business-industry/farmingfood/crops/manures',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/animalfeed/',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/fusarium/',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/mycotoxins-legislation/',
      '/business-industry/farmingfood/crops/mycotoxinsguidance/mycotoxinssampling',
      '/business-industry/farmingfood/dairy-guidance/',
      '/business-industry/farmingfood/dairy-guidance/cheeserecovery',
      '/business-industry/farmingfood/dairy-guidance/guidancemilktestantibioticres',
      '/business-industry/farmingfood/dairy-guidance/milk-hygiene-guide-for-milk-producers/',
      '/business-industry/farmingfood/dairy-guidance/rawmilkcream',
      '/business-industry/farmingfood/fish-shellfish/',
      '/business-industry/farmingfood/fish-shellfish/fish-shellfish-guidance/',
      '/business-industry/farmingfood/fish-shellfish/freezing-requirements-guidance/',
      '/business-industry/farmingfood/mycotoxins/',
      '/business-industry/farmingfood/mycotoxins/about/',
      '/business-industry/farmingfood/pesticides/',
      '/business-industry/farmingfood/pesticides/cropguides',
      '/business-industry/farmingfood/vetmeds/',
      '/business-industry/farmingfood/wildgameguidance/',
      '/business-industry/food-incidents/',
      '/business-industry/guidancenotes/food-law-controls-guidance/',
      '/business-industry/guidancenotes/guidance-farmers/',
      '/business-industry/guidancenotes/hygguid/',
      '/business-industry/guidancenotes/hygguid/ecoliguide',
      '/business-industry/guidancenotes/hygguid/eggenforcement',
      '/business-industry/guidancenotes/hygguid/euhygieneregulationsflexibilities/',
      '/business-industry/guidancenotes/hygguid/euhygieneregulationsflexibilities/flexexmig',
      '/business-industry/guidancenotes/hygguid/feed-activity-codes',
      '/business-industry/guidancenotes/hygguid/fhlguidance/',
      '/business-industry/guidancenotes/hygguid/fhlguidance/milkfarmhygni',
      '/business-industry/guidancenotes/hygguid/food-industry-guides',
      '/business-industry/guidancenotes/hygguid/foodhandlersguide',
      '/business-industry/guidancenotes/hygguid/fsactguide',
      '/business-industry/guidancenotes/hygguid/generalfoodlaw',
      '/business-industry/guidancenotes/hygguid/microbiolreg',
      '/business-industry/guidancenotes/hygguid/outbreakmanagement',
      '/business-industry/guidancenotes/hygguid/tempcontrolguidanceuk',
      '/business-industry/guidancenotes/hygguid/wastecookingoil',
      '/business-industry/guidancenotes/labelregsguidance/',
      '/business-industry/guidancenotes/labelregsguidance/allergenlabelguide2009',
      '/business-industry/guidancenotes/labelregsguidance/gmguidance',
      '/business-industry/guidancenotes/labelregsguidance/guidancelabellinggluten2010',
      '/business-industry/guidancenotes/labelregsguidance/labellingfoodcoloursreg13332008',
      '/business-industry/guidancenotes/labelregsguidance/maycontainguide',
      '/business-industry/guidancenotes/labelregsguidance/nonprepacked',
      '/business-industry/guidancenotes/meatregsguid/',
      '/business-industry/guidancenotes/meatregsguid/chargesguide',
      '/business-industry/guidancenotes/meatregsguid/coproductbyproductguide',
      '/business-industry/guidancenotes/meatregsguid/dsm-guidance',
      '/business-industry/guidancenotes/meatregsguid/emergencycattleslaughter',
      '/business-industry/guidancenotes/meatregsguid/farmgamehealth',
      '/business-industry/guidancenotes/meatregsguid/fcibovinetb',
      '/business-industry/guidancenotes/meatregsguid/fciguidance/',
      '/business-industry/guidancenotes/meatregsguid/fciguidance/fciew',
      '/business-industry/guidancenotes/meatregsguid/fciguidance/fciscot',
      '/business-industry/guidancenotes/meatregsguid/fciipoultry',
      '/business-industry/guidancenotes/meatregsguid/fcipigslaughter',
      '/business-industry/guidancenotes/meatregsguid/home-slaughter-livestock/',
      '/business-industry/guidancenotes/meatregsguid/home-slaughter-livestock/livestockguidance/',
      '/business-industry/guidancenotes/meatregsguid/illegalmeatguidance',
      '/business-industry/guidancenotes/meatregsguid/mincedmeatdays',
      '/business-industry/guidancenotes/meatregsguid/nitritesnitrates',
      '/business-industry/guidancenotes/meatregsguid/poultryslaughterauth',
      '/business-industry/guidancenotes/meatregsguid/snailguidance',
      '/business-industry/guidancenotes/meatregsguid/trichinellatestingwildboar',
      '/business-industry/guidancenotes/water-juice-guidance/',
      '/business-industry/guidancenotes/water-juice-guidance/natural-mineral-water',
      '/business-industry/how-to-make-an-appeal/',
      '/business-industry/how-to-make-an-appeal/panel/',
      '/business-industry/imports/',
      '/business-industry/imports/banned_restricted/',
      '/business-industry/imports/banned_restricted/aflatoxinreg11522009',
      '/business-industry/imports/banned_restricted/calabashchalk',
      '/business-industry/imports/banned_restricted/china',
      '/business-industry/imports/banned_restricted/chinarice',
      '/business-industry/imports/banned_restricted/guargumindia',
      '/business-industry/imports/banned_restricted/highrisknonpoao',
      '/business-industry/imports/banned_restricted/highrisknonpoao-91-2013',
      '/business-industry/imports/banned_restricted/import-betel-leaves',
      '/business-industry/imports/banned_restricted/japan',
      '/business-industry/imports/banned_restricted/kavakava',
      '/business-industry/imports/banned_restricted/kitchenware',
      '/business-industry/imports/banned_restricted/konjac',
      '/business-industry/imports/banned_restricted/milkandsoya-china',
      '/business-industry/imports/banned_restricted/pine-nuts-china/',
      '/business-industry/imports/banned_restricted/pine-nuts-china/pine-nut-exporters',
      '/business-industry/imports/banned_restricted/red2g',
      '/business-industry/imports/banned_restricted/restricted_foodstuffs',
      '/business-industry/imports/banned_restricted/spices',
      '/business-industry/imports/banned_restricted/sunflower',
      '/business-industry/imports/contacts/',
      '/business-industry/imports/contacts/imp_links/',
      '/business-industry/imports/importers/',
      '/business-industry/imports/importers/additivesimports',
      '/business-industry/imports/importers/contaminant/',
      '/business-industry/imports/importers/contaminant/Aflatoxin',
      '/business-industry/imports/importers/contaminant/soysauce',
      '/business-industry/imports/importers/ecguidance',
      '/business-industry/imports/importers/importsuppliers',
      '/business-industry/imports/importers/importtesting',
      '/business-industry/imports/importers/irradiated',
      '/business-industry/imports/importers/labelling',
      '/business-industry/imports/importers/legislation',
      '/business-industry/imports/importers/pointofentry',
      '/business-industry/imports/importers/redress/',
      '/business-industry/imports/importers/redress/redress1',
      '/business-industry/imports/importers/redress/redress2',
      '/business-industry/imports/importers/redress/redress3',
      '/business-industry/imports/importers/redress/redress4',
      '/business-industry/imports/importers/redress/redress5',
      '/business-industry/imports/importers/trade-samples-testing',
      '/business-industry/imports/personalimportsx/',
      '/business-industry/imports/want_to_import/',
      '/business-industry/imports/want_to_import/animalimports/',
      '/business-industry/imports/want_to_import/animalimports/dairy',
      '/business-industry/imports/want_to_import/animalimports/eggs',
      '/business-industry/imports/want_to_import/animalimports/gelatine',
      '/business-industry/imports/want_to_import/animalimports/honey',
      '/business-industry/imports/want_to_import/animalimports/meat',
      '/business-industry/imports/want_to_import/compositeprods',
      '/business-industry/imports/want_to_import/fisheryproducts/',
      '/business-industry/imports/want_to_import/tradeinfosheets',
      '/business-industry/manufacturers/',
      '/business-industry/manufacturers/additives-supps-guidance/',
      '/business-industry/manufacturers/additives-supps-guidance/foodadlegguid',
      '/business-industry/manufacturers/contaminants-fcm-guidance/',
      '/business-industry/manufacturers/contaminants-fcm-guidance/about-the-regulations/',
      '/business-industry/manufacturers/contaminants-fcm-guidance/foodmaterialarticleguidance2010',
      '/business-industry/manufacturers/contaminants-fcm-guidance/guidancefoodcontams09',
      '/business-industry/manufacturers/contaminants-fcm-guidance/legalcompliancefoodpackaging',
      '/business-industry/manufacturers/contaminants-fcm-guidance/legcontamfood',
      '/business-industry/manufacturers/myhaccp/',
      '/business-industry/manufacturers/shelf-life-storage/',
      '/business-industry/manufacturers/shelf-life-storage/quick-frozen-foodstuffs/',
      '/business-industry/manufacturers/shelf-life-storage/readytoeat',
      '/business-industry/manufacturers/shelf-life-storage/vacpac',
      '/business-industry/meat/',
      '/business-industry/meat/audit/',
      '/business-industry/meat/audit/auditprocess/',
      '/business-industry/meat/audit/auditprocess/auditprocess-prenov12',
      '/business-industry/meat/audit/concern',
      '/business-industry/meat/fci/',
      '/business-industry/meat/guidehygienemeat',
      '/business-industry/meat/haccpmeatplants/',
      '/business-industry/meat/haccpmeatplants/microbiologicalcriteria',
      '/business-industry/meat/meataudit/',
      '/business-industry/meat/trichinella-pigs/',
      '/business-industry/meat/trichinella-pigs/trichinella-pigs-testing/',
      '/business-industry/meat/trichinella-pigs/trichinella-pigs-testing/trichinella-testing-items/',
      '/business-industry/winestandards/',
      '/business-industry/winestandards/contactinspectors',
      '/business-industry/winestandards/lawguide/',
      '/business-industry/winestandards/lawguide/vineyards-wine-regs-summary/',
      '/business-industry/winestandards/lawguide/wine-regs-guidance/',
      '/business-industry/winestandards/lawguidex',
      '/business-industry/winestandards/ukvineyards',
      '/business-industry/winestandards/wine-documentary-checks/',
      '/business-industry/winestandards/wine-imports/',
      '/business-industry/winestandards/wine-labelling/',
      '/business-industry/winestandards/wineguidance/',
      '',

    );



  }

  return $url_list;
}

/**
 * Turn a list of urls into a tree
 * @param $url_list
 * @return array
 */
function FSA_menu_build_process_list($url_list){
  // initialise the tree
  $url_tree = array();
  // sort so that we have all urls in order
  sort($url_list, SORT_STRING);
  // process all urls to build a tree

  foreach ($url_list as $url) {
    // get rid of extra slashes
    $url = implode('/',explode('/', $url));
    FSA_menu_build_graft($url_tree, $url);
  }
 return $url_tree;
}

/**
 * Add a specific url to the tree
 * @param $tree
 * @param $url
 */
function FSA_menu_build_graft(&$url_tree, $url) {
  // move down the tree, until we get to the place we need to be
  // start at the root
  $branch = &$url_tree;
  $branch_url = array();
  foreach (explode('/', $url) as $fragment){
    $branch_url[] = $fragment;
    // if we need to create a new piece, initialise it
    // in case there is no node here, lets set the url
    if (!isset($branch[$fragment])) {
      $source_url = drupal_lookup_path('source', implode('/',$branch_url));
      $branch[$fragment]['#data']['url'] = implode('/',$branch_url);
      $branch[$fragment]['#data']['source_url'] = $source_url;
      $source_url_array = explode('/', $source_url);
      if ($source_url_array[0] == 'node') {
        // find the nid for the current node
        $branch[$fragment]['#data']['nid'] = $source_url_array[1];
      }
      // extract menu data
      if (isset($branch[$fragment]['#data']['nid'])) { // if we have a node we can use menu_node
        $branch[$fragment]['#data']['mlid'] = FSA_menu_build_get_main_menu_mlid($branch[$fragment]['#data']['nid']);
      }
      // set this to false until its actually the url requested, not just a fragment
      $branch['#data']['process'] = false;
    }
    $branch = &$branch[$fragment];
  }
  // mark this as a node that we should be processing
  $branch['#data']['process'] = true;
}

/**
 * Returns the menu link id for the main menu
 * @param $nid
 * @return int|string
 */
function FSA_menu_build_get_main_menu_mlid($nid) {
  $result = null;
  $links = menu_node_get_links($nid);
  if (is_array($links)) {
    // we found some menu links, now we need to make sure we have the correct menu
    foreach ($links as $mlid => $link_data) {
      if ($link_data->menu_name =='main-menu') {
        $result = $mlid;
      }
    }
  }
  return $result;
}


/**
 * Walk through the url tree and assign menu parents to nodes.
 * @param $url_tree
 */
function FSA_menu_build_assign(&$url_tree, $plid = 0) {

  // if we have a parent link
  // check to see if we should process the current node
  // and make sure that the current node does not already have a main menu entry
  if (isset($url_tree['#data']) && $url_tree['#data']['process'] && !isset($url_tree['#data']['mlid'])) {
    //? what if we have no plid?
    $node = node_load($url_tree['#data']['nid']);
    $node->menu = array(
      'link_title' =>  $node->title, #todo short title
      'enabled' => 1,
      'plid' => $plid,
      'menu_name' => 'main-menu'
    );
    // enable pathauto
    $node->path['pathauto'] = true;
    // save the node with the new menu parent
    node_save($node);
    // get the menu link id from the new node
    if ($mlid = FSA_menu_build_get_main_menu_mlid($node->nid)) {
      $url_tree['#data']['mlid'] = $mlid;
    }
  }
  else if (isset($url_tree['#data']) && isset($url_tree['#data']['mlid'])) {
    // we have already got a menu link
    $mlid = $url_tree['#data']['mlid'];
  }
  // if by this point we have not got a menu id, pass the parent one on
  if (!isset($mlid)) {
    $mlid = $plid;
  }

  // go through all the keys at this level - except the data for this level
  foreach ($url_tree as  $key => &$branch) {
    if ($key != '#data') { // skip the data branch
      // if we have a menu item, we will keep it
      FSA_menu_build_assign($branch, $mlid);
    }
  }


}


/*
 *
 *
node->menu
-> enabled = 1
-> mlid
-> parent (main-menu:plid)

       menu_name = "main-menu"
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => $menu_name,
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
 *
 */