<?php
/**
 * @file
 * Module file for accessibility_links.
 */

/**
 * Implements hook_block_info().
 */
function behat_custom_block_info() {
  $blocks['behat'] = array(
    'info' => t('Behat data'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function behat_custom_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'behat':
      $content[] = "<!-- Behat testing info -->";

      // get current user
      if (isset($GLOBALS['user']->name)) {
        $content[] = "<!-- drupal username:". $GLOBALS['user']->name . "  -->";
      }

      // node id
      if (arg(0) == 'node' && is_numeric(arg(1))) {
        $content[] = "<!-- drupal nid:". arg(1) . "  -->";
      }

      $block['subject'] = NULL;
      $block['content'] = array(
        '#markup' => implode($content),
      );
  }
  return $block;
}


