<?php
/**
 * @file
 * Module code for the FSA feedback module.
 */

/**
 * Set the region in which the feedback form will appear.
 */
define('FSA_FEEDBACK_REGION', 'node_inline');


/**
 * Implements hook_page_build().
 *
 * @param $page
 *   Nested array of renderable elements that make up the page.
 */
function fsa_feedback_page_build(&$page) {

  // First check that the feedback element exists. If not, exit now.
  if (empty($page[FSA_FEEDBACK_REGION]['feedback'])) {
    return;
  }

  // Add the custom CSS file and make sure it comes after the contrib one.
  $page[FSA_FEEDBACK_REGION]['feedback']['#attached']['css'][drupal_get_path('module', 'fsa_feedback') . '/fsa-feedback.css'] = array(
    'group' => 'theme',
    'weight' => 100,
  );

}



/**
 * Implements hook_form_alter().
 */
function fsa_feedback_form_feedback_form_alter(&$form, &$form_state, $form_id) {
  // Wrap the feedback form in a div and add a class. This will implement
  // styling as seen on other FSA forms.
  $form['#prefix'] = '<div class="grey-container-block">';
  $form['#suffix'] = '</div>';
  $form['#attributes']['class'][] = 'custom-block-inner';
}
