name = Site Frontend One Column
description = 12 Column grid layout with main content and no sidebars
template = site-frontend-one-column-layout
preview = preview.png

; Regions - these also need to exist in site_frontend.info
regions[header_top_banner] = Top banner
regions[header_branding] = Header Branding
regions[header_top_menu] = Header Top Menu
regions[header_search] = Header Search
regions[header_main_menu] = Header Main Menu
regions[header_social_media] = Header Social Media
regions[breadcrumb] = Breadcrumb
regions[accessibility] = Accessibility
regions[preface] = Preface
regions[content_top] = Content Top
regions[system_highlighted] = System Highlighted
regions[system_help] = System Help
regions[content] = Content
; regions[sidebar_first] = First Sidebar
; regions[sidebar_second] = Second Sidebar
regions[bottom_menu] = Bottom Menu
regions[footer_social_media] = Footer Social Media
regions[footer_copyright] = Footer Copyright
regions[footer_menu] = Footer Menu
regions[footer_buttons] = Footer Buttons

; following region is rendered in node.tpl.php for some content types
regions[node_inline] = Node Inline

; Styles
stylesheets[all][] = css/layouts/site-frontend-one-column/site-frontend-one-column.layout.css
stylesheets[all][] = css/layouts/site-frontend-one-column/site-frontend-one-column.layout.no-query.css
