name = Site Frontend Campaign Landing Page
description = Campaign landing page layout
template = site-frontend-campaign-landing-page-layout
preview = preview.png

; Regions - these also need to exist in site_frontend.info
regions[header_branding] = Header Branding
regions[header_top_menu] = Header Top Menu
regions[header_search] = Header Search
regions[header_main_menu] = Header Main Menu
regions[header_social_media] = Header Social Media
regions[breadcrumb] = Breadcrumb
regions[accessibility] = Accessibility
regions[preface] = Preface
regions[content_top] = Content Top
regions[system_highlighted] = System Highlighted
regions[system_help] = System Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[bottom_menu] = Bottom Menu
regions[footer_copyright] = Footer Copyright
regions[footer_menu] = Footer Menu
regions[footer_buttons] = Footer Buttons
regions[campaign_promotions] = Campaign promotions

; following region is rendered in node.tpl.php for some content types
regions[node_inline] = Node Inline

; Styles
stylesheets[all][] = css/layouts/site-frontend-three-column/site-frontend-three-column.layout.css
stylesheets[all][] = css/layouts/site-frontend-three-column/site-frontend-three-column.layout.no-query.css